from .user import UserViewset
from .nivel import NivelViewset
from .grado import GradoViewset
from .estudiante import EstudianteViewset
from .rol import RolViewset
from .profesion import ProfesionViewset
from .catedratico import CatedraticoteViewset
from .seccion import SeccionViewset
from .curso import CursoViewset
from .cicloEscolar import CicloEscolarViewset
from .asignacion import AsignacionViewset