# Generated by Django 2.2.13 on 2021-03-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210315_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='imagen_portada',
            field=models.FileField(blank=True, null=True, upload_to='Imagenes'),
        ),
    ]
