from .profile import Profile
from .m_users import User
from .rol import Rol
from .asignacion import Asignacion
from .catedratico import Catedratico
from .cicloEscolar import CicloEscolar
from .curso import Curso
from .estudiante import Estudiante
from .evento import Evento
from .grado import Grado
from .materialClase import MaterialClase
from .nivel import Nivel
from .profesion import Profesion
from .seccion import Seccion
from .tarea import Tarea
from .tareaEstudiante import TareaEstudiante
from .vehiculo import Vehiculo
from .servicio import Servicio
